"""empty message

Revision ID: 967aaa188f2a
Revises: 
Create Date: 2023-05-24 20:21:53.960504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967aaa188f2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('subject_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('target_grade', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('major_seats', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('other_seats', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('minor_seats', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('professor', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('schedule', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('schedule')
        batch_op.drop_column('professor')
        batch_op.drop_column('minor_seats')
        batch_op.drop_column('other_seats')
        batch_op.drop_column('major_seats')
        batch_op.drop_column('target_grade')
        batch_op.drop_column('subject_code')
        batch_op.drop_column('subject')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
