"""empty message

Revision ID: f838f54bf17a
Revises: 74fd21c29fef
Create Date: 2023-05-28 16:23:27.310417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f838f54bf17a'
down_revision = '74fd21c29fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('target_grade', sa.String(length=10), nullable=False),
    sa.Column('major_seats', sa.Integer(), nullable=False),
    sa.Column('other_seats', sa.Integer(), nullable=False),
    sa.Column('minor_seats', sa.Integer(), nullable=False),
    sa.Column('professor', sa.String(length=80), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_user_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_user_association')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
